(()=>{
'use strict';
/* =============================================================
   VITAFOAM ERP - Module intégré Production + Stock + Budget
   Backend: Supabase PostgreSQL
   ============================================================= */
let currentOFId = null;
let currentOFData = null;
let currentDebitageInputKg = 0;
let bomState = { id:null, parent:null, mps:[] };

const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = v => Number(v || 0);
const nfmt = (v,d=3) => Number(v||0).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d});
function banner(id,msg,type='info'){ const e=document.getElementById(id); if(!e)return; e.textContent=msg; e.className='art-banner '+type; e.style.display='block'; }
function hideBanner(id){ const e=document.getElementById(id); if(e)e.style.display='none'; }
function statusLabel(s){ return ({PLANIFIE:'Planifié',VIKING_EN_COURS:'Viking en cours',A_DEBITER:'À débiter',DEBITAGE_EN_COURS:'Débitage en cours',A_CONFECTIONNER:'À confectionner',CONFECTION_EN_COURS:'Confection en cours',TERMINE:'Terminé',CLOTURE:'Clôturé'})[s]||s; }
function statusStage(s){ if(['PLANIFIE','VIKING_EN_COURS'].includes(s))return 1;if(['A_DEBITER','DEBITAGE_EN_COURS'].includes(s))return 2;if(['A_CONFECTIONNER','CONFECTION_EN_COURS'].includes(s))return 3;return 4; }
async function qArticles(types){ let q=supabaseClient.from('articles').select('*').eq('active',true).order('code'); if(types?.length)q=q.in('article_type',types); const {data,error}=await q; if(error)throw error; return data||[]; }

// ---------- Dashboard production réel ----------
async function renderDashboard(){
  const kpi=document.getElementById('kpi-grid'), tbody=document.getElementById('of-table-body');
  if(kpi)kpi.innerHTML='<div class="kpi-card"><div class="label">Chargement</div><div class="value">…</div></div>';
  if(tbody)tbody.innerHTML='<tr><td colspan="8">Chargement des OF…</td></tr>';
  const {data,error}=await supabaseClient.from('v_of_summary').select('*').order('created_at',{ascending:false});
  if(error){ if(tbody)tbody.innerHTML=`<tr><td colspan="8" class="danger-text">${esc(error.message)}</td></tr>`; return; }
  const rows=data||[];
  const active=rows.filter(r=>!['TERMINE','CLOTURE'].includes(r.status)).length;
  const finished=rows.reduce((s,r)=>s+num(r.finished_pcs),0);
  const dry=rows.reduce((s,r)=>s+num(r.weight_after_drying_kg),0);
  const waste=rows.reduce((s,r)=>s+num(r.wastes_kg)+num(r.souple_kg),0);
  const yieldPct=dry>0?Math.max(0,(dry-waste)/dry*100):0;
  const barsEl=document.getElementById('bars'); const titleEl=document.getElementById('chart-title');
  if(titleEl)titleEl.textContent='Rendement matière & taux de chute — derniers OF débités';
  if(barsEl){const recent=rows.filter(r=>num(r.weight_after_drying_kg)>0).slice(0,7).reverse();barsEl.innerHTML=recent.map(r=>{const d=num(r.weight_after_drying_kg),w=num(r.wastes_kg)+num(r.souple_kg),c=d?Math.min(100,w/d*100):0,y=Math.max(0,100-c);return `<div class="bar-col"><div class="bar-stack" style="height:${Math.max(25,Math.round(y*1.6))}px"><div class="bar-seg" style="height:${Math.max(2,Math.round(c*1.6))}px;background:var(--gold)"></div><div class="bar-seg" style="height:${Math.max(4,Math.round((y-c>0?y-c:y)*1.2))}px;background:var(--navy)"></div></div><div class="m-label">${esc(r.of_number.slice(-4))}</div></div>`}).join('')||'<div class="mini-note">Les graphiques apparaîtront après les premiers OF débités.</div>';}
  if(kpi)kpi.innerHTML=`
    <div class="kpi-card"><div class="label">OF total</div><div class="value">${rows.length}</div><div class="delta">${active} en cours</div></div>
    <div class="kpi-card"><div class="label">PF réalisés</div><div class="value">${finished}</div><div class="delta">pièces issues des OF</div></div>
    <div class="kpi-card"><div class="label">Poids après séchage</div><div class="value">${nfmt(dry,1)}</div><div class="delta">kg transférés au débitage</div></div>
    <div class="kpi-card"><div class="label">Rendement matière indicatif</div><div class="value">${yieldPct.toFixed(1)}%</div><div class="delta">souple inclus dans chute ligne</div></div>`;
  if(tbody){
    if(!rows.length){tbody.innerHTML='<tr><td colspan="8">Aucun OF. Créez votre premier OF Bloc.</td></tr>';return;}
    tbody.innerHTML=rows.map(r=>`<tr class="click-row" data-of-id="${r.id}"><td><button class="of-link" data-of-id="${r.id}">${esc(r.of_number)}</button></td><td>${statusStage(r.status)===1?'Viking/Séchoir':statusStage(r.status)===2?'Débitage':statusStage(r.status)===3?'Confection':'Stock PF'}</td><td><span class="badge ${['TERMINE','CLOTURE'].includes(r.status)?'clos':r.status==='A_DEBITER'?'ferme':'en-cours'}">${esc(statusLabel(r.status))}</span></td><td>BLOC</td><td>${esc(r.block_code)} — ${esc(r.block_designation)}</td><td>${r.planned_blocks} bloc(s)</td><td>${r.finished_pcs||0} PF</td><td>${nfmt(r.weight_after_drying_kg,1)} kg</td></tr>`).join('');
    tbody.querySelectorAll('[data-of-id]').forEach(x=>x.addEventListener('click',()=>openOF(x.dataset.ofId)));
  }
}

// ---------- Nouvel OF ----------
async function initOFCreate(){
  const sel=document.getElementById('of-block-article'); if(!sel)return;
  try{ const blocks=await qArticles(['BLOC']); sel.innerHTML=blocks.map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.designation||a.intitule)}</option>`).join('');
    const d=document.getElementById('of-date-plan'); if(d&&!d.value)d.value=new Date().toISOString().slice(0,10);
  }catch(e){banner('of-new-banner',e.message,'warning')}
}
async function createOF(){
  hideBanner('of-new-banner'); const article=document.getElementById('of-block-article').value, qty=+document.getElementById('of-planned-blocks').value, site=document.getElementById('of-site').value, planned=document.getElementById('of-date-plan').value, notes=document.getElementById('of-notes').value.trim();
  if(!article||qty<=0)return banner('of-new-banner','Sélectionnez un bloc et une quantité valide.','warning');
  const btn=document.getElementById('of-create-btn');btn.disabled=true;btn.textContent='Création…';
  const {data,error}=await supabaseClient.rpc('create_production_order',{p_block_article_id:article,p_planned_blocks:qty,p_notes:notes||null,p_site:site,p_planned_date:planned||null}); btn.disabled=false;btn.textContent="Créer l'OF et figer le standard";
  if(error)return banner('of-new-banner',error.message,'warning'); banner('of-new-banner','✅ OF créé. Le standard a été figé.','success'); await openOF(data);
}

// ---------- Nomenclatures ----------
async function initBom(){
  const parent=document.getElementById('bom-parent'); if(!parent)return;
  try{const all=await qArticles(['BLOC','MP']); const blocks=all.filter(a=>a.article_type==='BLOC'); bomState.mps=all.filter(a=>a.article_type==='MP'); parent.innerHTML=blocks.map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.designation||a.intitule)}</option>`).join(''); if(blocks[0]){parent.value=blocks[0].id;await loadBom(blocks[0].id)}}catch(e){banner('bom-banner',e.message,'warning')}
}
async function loadBom(parentId){
  hideBanner('bom-banner'); bomState.parent=parentId; const {data:h,error}=await supabaseClient.from('bom_headers').select('*').eq('parent_article_id',parentId).eq('active',true).order('version',{ascending:false}).limit(1).maybeSingle(); if(error)return banner('bom-banner',error.message,'warning');
  bomState.id=h?.id||null; document.getElementById('bom-version').value=h?.version||1; let vals={}; if(h){const {data:l}=await supabaseClient.from('bom_lines').select('*').eq('bom_id',h.id);(l||[]).forEach(x=>vals[x.component_id]=x.qty_standard)}
  document.getElementById('bom-lines-body').innerHTML=bomState.mps.map(m=>`<tr><td><strong>${esc(m.code)}</strong></td><td>${esc(m.designation||m.intitule)}</td><td>${esc(m.unite)}</td><td><input class="bom-qty" data-id="${m.id}" type="number" min="0" step="0.0001" value="${vals[m.id]??''}" placeholder="0"></td></tr>`).join('');
}
async function saveBom(){
  const parent=bomState.parent, version=+document.getElementById('bom-version').value||1; if(!parent)return; hideBanner('bom-banner');
  let id=bomState.id;
  if(!id){const {data,error}=await supabaseClient.from('bom_headers').insert({parent_article_id:parent,version,active:true,notes:'Standard créé depuis ERP'}).select('id').single();if(error)return banner('bom-banner',error.message,'warning');id=data.id;}
  else{const {error}=await supabaseClient.from('bom_headers').update({version,updated_at:new Date().toISOString()}).eq('id',id);if(error&&error.code!=='42703')return banner('bom-banner',error.message,'warning')}
  const {error:del}=await supabaseClient.from('bom_lines').delete().eq('bom_id',id);if(del)return banner('bom-banner',del.message,'warning');
  const lines=[...document.querySelectorAll('.bom-qty')].map(x=>({bom_id:id,component_id:x.dataset.id,qty_standard:num(x.value),unite:bomState.mps.find(m=>m.id===x.dataset.id)?.unite||'kg'})).filter(x=>x.qty_standard>0);
  if(lines.length){const {error}=await supabaseClient.from('bom_lines').insert(lines);if(error)return banner('bom-banner',error.message,'warning')}
  bomState.id=id;banner('bom-banner','✅ Nomenclature enregistrée. Elle servira de référence aux prochains OF.','success');
}

// ---------- Fiche OF ----------
async function openOF(id){ currentOFId=id; showView('of-detail'); await loadOFDetail(); }
async function loadOFDetail(){
  if(!currentOFId)return; hideBanner('ofd-banner');
  const {data:of,error}=await supabaseClient.from('production_orders').select('*, block:articles!production_orders_block_article_id_fkey(*)').eq('id',currentOFId).single(); if(error)return banner('ofd-banner',error.message,'warning');
  currentOFData=of; document.getElementById('ofd-title').textContent=of.of_number; document.getElementById('ofd-subtitle').textContent=`${of.block?.code||''} — ${of.block?.designation||of.block?.intitule||''} · ${of.planned_blocks} bloc(s) prévus · ${of.site||'—'}`; document.getElementById('ofd-status').textContent=statusLabel(of.status);
  const stage=statusStage(of.status);document.getElementById('ofd-flow').innerHTML=['OF Bloc','Viking / Séchoir','Débitage / Tamponnage','Confection','Stock PF'].map((x,i)=>`${i?'<span class="prod-arrow">→</span>':''}<span class="prod-step ${i<stage?'done':i===stage?'current':''}">${x}</span>`).join('');
  const [stdQ,vQ,wQ,dQ,oQ,dwQ,bQ,cQ,mQ]=await Promise.all([
    supabaseClient.from('production_order_standards').select('*,article:articles!production_order_standards_component_id_fkey(*)').eq('of_id',currentOFId),
    supabaseClient.from('viking_runs').select('*').eq('of_id',currentOFId).maybeSingle(),
    supabaseClient.from('block_weighings').select('*').eq('of_id',currentOFId).order('block_no'),
    supabaseClient.from('debitage_runs').select('*').eq('of_id',currentOFId).maybeSingle(),
    supabaseClient.from('debitage_outputs').select('*,article:articles!debitage_outputs_article_id_fkey(*)').eq('of_id',currentOFId),
    supabaseClient.from('debitage_wastes').select('*').eq('of_id',currentOFId),
    supabaseClient.from('confection_batches').select('*,finished:articles!confection_batches_finished_article_id_fkey(*)').eq('of_id',currentOFId),
    supabaseClient.from('viking_consumptions').select('*').eq('of_id',currentOFId),
    supabaseClient.from('stock_movements').select('*,article:articles!stock_movements_article_id_fkey(*)').eq('of_id',currentOFId).order('created_at',{ascending:false})
  ]);
  const standards=stdQ.data||[],v=vQ.data,weigh=wQ.data||[],dr=dQ.data,outs=oQ.data||[],wastes=dwQ.data||[],batches=bQ.data||[],vcons=cQ.data||[],moves=mQ.data||[];
  const dry=weigh.reduce((s,x)=>s+num(x.weight_kg),0), wasteKg=wastes.reduce((s,x)=>s+num(x.weight_kg),0), souple=outs.filter(x=>x.output_type==='SOUPLE').reduce((s,x)=>s+num(x.weight_kg),0), pf=batches.reduce((s,x)=>s+num(x.qty_finished),0);
  document.getElementById('ofd-summary').innerHTML=`<div class="kpi-card"><div class="label">Prévu</div><div class="value">${of.planned_blocks}</div><div class="delta">blocs</div></div><div class="kpi-card"><div class="label">Après séchage</div><div class="value">${nfmt(dry,1)}</div><div class="delta">kg</div></div><div class="kpi-card"><div class="label">Chutes ligne</div><div class="value">${nfmt(wasteKg+souple,1)}</div><div class="delta">kg, souple inclus</div></div><div class="kpi-card"><div class="label">Produit fini</div><div class="value">${pf}</div><div class="delta">pièces</div></div>`;
  renderOFStandard(standards,vcons); renderOFViking(of,standards,v,weigh); await renderOFDebitage(of,dr,outs,wastes,dry); await renderOFConfection(of,outs,batches); renderOFTrace(moves);
}
function renderOFStandard(std,vcons){const vm=Object.fromEntries(vcons.map(x=>[x.component_id,x]));document.getElementById('ofd-tab-standard').innerHTML=`<div class="panel"><div class="panel-head"><h3>Standard figé de l'OF</h3></div><div class="table-scroll"><table><thead><tr><th>MP</th><th>Std/bloc</th><th>Prévu OF</th><th>Réel</th><th>Écart</th><th>PRU</th><th>Valeur</th></tr></thead><tbody>${std.map(x=>{const c=vm[x.component_id];return `<tr><td>${esc(x.article?.code)} — ${esc(x.article?.designation||x.article?.intitule)}</td><td>${x.qty_per_block} ${x.unite}</td><td>${x.qty_planned}</td><td>${c?.actual_qty??'—'}</td><td>${c?(num(c.actual_qty)-num(x.qty_planned)).toFixed(3):'—'}</td><td>${c?fmtMga(num(c.pru)):'—'}</td><td>${c?fmtMga(num(c.value)):'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function renderOFViking(of,std,v,weigh){const target=document.getElementById('ofd-tab-viking');if(v){target.innerHTML=`<div class="panel"><div class="panel-head"><h3>Viking / Séchoir validé</h3></div><div class="info-grid"><div class="info-box"><div class="label">Blocs produits</div><div class="value">${v.produced_blocks}</div></div><div class="info-box"><div class="label">Conformes</div><div class="value">${v.conform_blocks}</div></div><div class="info-box"><div class="label">Têtes de bloc</div><div class="value">${v.head_blocks}</div></div><div class="info-box"><div class="label">Blocs NC</div><div class="value">${v.nonconforming_blocks}</div></div><div class="info-box"><div class="label">Autres chutes</div><div class="value">${v.other_waste_kg} kg</div></div><div class="info-box"><div class="label">Poids après séchage</div><div class="value">${nfmt(weigh.reduce((s,x)=>s+num(x.weight_kg),0),3)} kg</div></div></div><div class="table-scroll"><table><thead><tr><th>Bloc</th><th>Poids après séchage</th></tr></thead><tbody>${weigh.map(w=>`<tr><td>Bloc ${w.block_no}</td><td>${w.weight_kg} kg</td></tr>`).join('')}</tbody></table></div></div>`;return;}
  if(of.status!=='PLANIFIE'){target.innerHTML='<div class="panel"><div style="padding:22px">Aucune saisie Viking modifiable pour ce statut.</div></div>';return;}
  target.innerHTML=`<div class="panel"><div class="panel-head"><h3>1 · Saisie Viking puis pesée après Séchoir</h3></div><div style="padding:22px"><div class="three-col"><div class="field"><label>Blocs produits</label><input id="vik-produced" type="number" min="0" value="${of.planned_blocks}"></div><div class="field"><label>Blocs conformes à sécher</label><input id="vik-conform" type="number" min="0" value="${of.planned_blocks}"></div><div class="field"><label>Têtes de bloc</label><input id="vik-head" type="number" min="0" value="0"></div><div class="field"><label>Blocs non conformes</label><input id="vik-nc" type="number" min="0" value="0"></div><div class="field"><label>Autres chutes (kg)</label><input id="vik-other" type="number" min="0" step="0.001" value="0"></div></div><h3>Consommations MP réelles</h3><div class="table-scroll"><table class="input-table"><thead><tr><th>MP</th><th>Prévu</th><th>Réel</th><th>PRU Ar</th></tr></thead><tbody>${std.map(x=>`<tr><td>${esc(x.article?.code)} — ${esc(x.article?.designation||x.article?.intitule)}</td><td>${x.qty_planned} ${x.unite}</td><td><input class="vik-real" data-id="${x.component_id}" type="number" min="0" step="0.0001" value="${x.qty_planned}"></td><td><input class="vik-pru" data-id="${x.component_id}" type="number" min="0" step="0.01" value="${x.article?.pru_reference||0}"></td></tr>`).join('')}</tbody></table></div><h3>Pesée après séchage</h3><p class="mini-note">Le nombre de lignes doit correspondre au nombre de blocs conformes. Le total devient automatiquement l'entrée du Débitage.</p><div id="vik-weighings"></div><div class="form-actions" style="justify-content:flex-start"><button id="vik-validate" class="btn-create">Valider Viking/Séchoir et transférer au Débitage</button></div></div></div>`;
  const cf=document.getElementById('vik-conform');const draw=()=>{const n=+cf.value||0;document.getElementById('vik-weighings').innerHTML=`<div class="table-scroll"><table class="input-table"><thead><tr><th>N° bloc</th><th>Poids après séchage (kg)</th></tr></thead><tbody>${Array.from({length:n},(_,i)=>`<tr><td>${i+1}</td><td><input class="vik-weight" data-no="${i+1}" type="number" min="0.001" step="0.001" required></td></tr>`).join('')}</tbody></table></div>`};cf.addEventListener('change',draw);draw();document.getElementById('vik-validate').addEventListener('click',validateViking);
}
async function validateViking(){const cons=[...document.querySelectorAll('.vik-real')].map(x=>({component_id:x.dataset.id,actual_qty:num(x.value),pru:num(document.querySelector(`.vik-pru[data-id="${x.dataset.id}"]`).value)}));const weights=[...document.querySelectorAll('.vik-weight')].map(x=>({block_no:+x.dataset.no,weight_kg:num(x.value)}));if(weights.some(x=>x.weight_kg<=0))return banner('ofd-banner','Saisissez le poids de chaque bloc après séchage.','warning');const args={p_of_id:currentOFId,p_produced_blocks:+document.getElementById('vik-produced').value,p_conform_blocks:+document.getElementById('vik-conform').value,p_head_blocks:+document.getElementById('vik-head').value,p_nonconforming_blocks:+document.getElementById('vik-nc').value,p_other_waste_kg:num(document.getElementById('vik-other').value),p_notes:null,p_consumptions:cons,p_weighings:weights};const {error}=await supabaseClient.rpc('validate_viking',args);if(error)return banner('ofd-banner',error.message,'warning');banner('ofd-banner','✅ Viking/Séchoir validé. Le poids pesé est transféré au Débitage.','success');await loadOFDetail();}
async function renderOFDebitage(of,dr,outs,wastes,inputKg){const t=document.getElementById('ofd-tab-debitage');if(dr){t.innerHTML=`<div class="panel"><div class="panel-head"><h3>Débitage / Tamponnage validé</h3></div><div class="info-grid"><div class="info-box"><div class="label">Entrée</div><div class="value">${nfmt(dr.input_weight_kg)} kg</div></div><div class="info-box"><div class="label">Écart bilan</div><div class="value">${nfmt(dr.material_gap_kg)} kg</div></div></div><div class="table-scroll"><table><thead><tr><th>Type</th><th>Article</th><th>Pièces</th><th>Kg</th></tr></thead><tbody>${outs.map(o=>`<tr><td>${o.output_type}</td><td>${esc(o.article?.code)}</td><td>${o.qty_pcs}</td><td>${o.weight_kg}</td></tr>`).join('')}${wastes.map(w=>`<tr><td>CHUTE ${w.waste_type}</td><td>—</td><td>—</td><td>${w.weight_kg}</td></tr>`).join('')}</tbody></table></div></div>`;return;}if(of.status!=='A_DEBITER'){t.innerHTML='<div class="panel"><div style="padding:22px">Le Débitage sera disponible après validation Viking/Séchoir.</div></div>';return;}
  currentDebitageInputKg=num(inputKg);
  const semi=await qArticles(['SEMI_FINI']); t.innerHTML=`<div class="panel"><div class="panel-head"><h3>2 · Débitage / Tamponnage</h3></div><div style="padding:22px"><div class="art-banner info">Entrée automatique : <strong>${nfmt(inputKg)} kg</strong> après séchage. Ne pas ressaisir.</div><h3>Sorties vers Confection</h3><div id="deb-outs"></div><button class="logout-btn" id="deb-add">+ Ajouter une référence/dimension</button><h3 style="margin-top:20px">Chutes constatées au Débitage</h3><div class="form-grid"><div class="field"><label>Croûte kg</label><input id="deb-croute" type="number" min="0" step="0.001" value="0"></div><div class="field"><label>Chemelle kg</label><input id="deb-chemelle" type="number" min="0" step="0.001" value="0"></div><div class="field"><label>Filement kg</label><input id="deb-filement" type="number" min="0" step="0.001" value="0"></div><div class="field"><label>Autres kg</label><input id="deb-other" type="number" min="0" step="0.001" value="0"></div></div><div id="deb-balance" class="art-banner info"></div><div class="form-actions" style="justify-content:flex-start"><button id="deb-validate" class="btn-create">Valider et transférer à Confection</button></div></div></div>`;
  const holder=document.getElementById('deb-outs');let idx=0;const add=()=>{const row=document.createElement('div');row.className='form-grid modal-ish deb-row';row.dataset.i=String(idx++);row.innerHTML=`<div class="field"><label>Article semi-fini</label><select class="deb-article">${semi.map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.designation||a.intitule)}</option>`).join('')}</select></div><div class="field"><label>Type</label><select class="deb-type"><option value="CONFORME">Conforme tamponné</option><option value="SOUPLE">Souple non tamponné (chute valorisable)</option></select></div><div class="field"><label>Pièces</label><input class="deb-pcs" type="number" min="0" value="0"></div><div class="field"><label>Poids kg</label><input class="deb-kg" type="number" min="0" step="0.001" value="0"></div>`;holder.appendChild(row);row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',updateDebBalance));};document.getElementById('deb-add').addEventListener('click',add);['deb-croute','deb-chemelle','deb-filement','deb-other'].forEach(id=>document.getElementById(id).addEventListener('input',updateDebBalance));add();updateDebBalance();document.getElementById('deb-validate').addEventListener('click',()=>validateDebitage(inputKg));
}
function updateDebBalance(){if(!document.getElementById('deb-balance'))return;const dry=num(currentDebitageInputKg);const out=[...document.querySelectorAll('.deb-kg')].reduce((s,x)=>s+num(x.value),0);const w=['deb-croute','deb-chemelle','deb-filement','deb-other'].reduce((s,id)=>s+num(document.getElementById(id)?.value),0);const gap=dry-out-w;const e=document.getElementById('deb-balance');e.className='art-banner '+(Math.abs(gap)<=0.05?'success':'warning');e.textContent=`Bilan matière : entrée ${nfmt(dry)} kg − sorties/chutes ${nfmt(out+w)} kg = écart ${nfmt(gap)} kg`;}
async function validateDebitage(inputKg){const outputs=[...document.querySelectorAll('.deb-row')].map(r=>({article_id:r.querySelector('.deb-article').value,output_type:r.querySelector('.deb-type').value,qty_pcs:+r.querySelector('.deb-pcs').value,weight_kg:num(r.querySelector('.deb-kg').value)})).filter(x=>x.qty_pcs>0||x.weight_kg>0);if(!outputs.length)return banner('ofd-banner','Ajoutez au moins une sortie conforme ou souple.','warning');const wastes=[['CROUTE','deb-croute'],['CHEMELLE','deb-chemelle'],['FILEMENT','deb-filement'],['AUTRE','deb-other']].map(([w,id])=>({waste_type:w,weight_kg:num(document.getElementById(id).value)}));const {error}=await supabaseClient.rpc('validate_debitage',{p_of_id:currentOFId,p_outputs:outputs,p_wastes:wastes,p_notes:null,p_tolerance_kg:0.05});if(error)return banner('ofd-banner',error.message,'warning');banner('ofd-banner','✅ Débitage validé. Conforme et souple transférés à Confection.','success');await loadOFDetail();}
async function renderOFConfection(of,outs,batches){const t=document.getElementById('ofd-tab-confection');if(!['A_CONFECTIONNER','CONFECTION_EN_COURS','TERMINE','CLOTURE'].includes(of.status)){t.innerHTML='<div class="panel"><div style="padding:22px">La Confection sera disponible après validation du Débitage.</div></div>';return;}const pfs=await qArticles(['PF']),psfs=await qArticles(['PSF']);const used={};batches.forEach(b=>used[b.source_output_id]=(used[b.source_output_id]||0)+num(b.qty_input));const open=outs.filter(o=>num(o.qty_pcs)-num(used[o.id])>0);t.innerHTML=`<div class="panel"><div class="panel-head"><h3>3 · Confection</h3></div><div style="padding:22px">${batches.length?`<div class="art-banner success">${batches.reduce((s,b)=>s+num(b.qty_finished),0)} PF déjà entrés en stock.</div>`:''}${open.length?`<div class="field"><label>Sortie Débitage à traiter</label><select id="conf-source">${open.map(o=>`<option value="${o.id}">${esc(o.article?.code)} — ${o.output_type} — disponible ${num(o.qty_pcs)-num(used[o.id])} pcs</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label>Produit fini</label><select id="conf-pf">${pfs.map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.designation||a.intitule)}</option>`).join('')}</select></div><div class="field"><label>Finition</label><select id="conf-finish"><option value="TISSU_GAINE">Tissu + gaine</option><option value="GAINE_SEULE">Gaine seule</option></select></div><div class="field"><label>Qté entrée</label><input id="conf-in" type="number" min="1"></div><div class="field"><label>PF obtenu</label><input id="conf-pfqty" type="number" min="0"></div><div class="field"><label>Rebut</label><input id="conf-reject" type="number" min="0" value="0"></div></div><h3>Consommations PSF</h3><div class="table-scroll"><table class="input-table"><thead><tr><th>PSF</th><th>Qté réelle</th><th>PRU Ar</th></tr></thead><tbody>${psfs.map(a=>`<tr><td>${esc(a.code)} — ${esc(a.designation||a.intitule)}</td><td><input class="conf-real" data-id="${a.id}" type="number" min="0" step="0.0001" value="0"></td><td><input class="conf-pru" data-id="${a.id}" type="number" min="0" step="0.01" value="${a.pru_reference||0}"></td></tr>`).join('')}</tbody></table></div><div class="form-actions" style="justify-content:flex-start"><button id="conf-validate" class="btn-create">Valider ce lot et entrer le PF en stock</button></div>`:'<div class="art-banner success">Toutes les sorties Débitage ont été traitées.</div>'}<div class="form-actions" style="justify-content:flex-start"><button id="conf-close" class="logout-btn">Clôturer l’OF</button></div></div></div>`;
  if(open.length){const src=document.getElementById('conf-source'),fill=()=>{const o=open.find(x=>x.id===src.value)||open[0];const avail=num(o.qty_pcs)-num(used[o.id]);document.getElementById('conf-in').value=avail;document.getElementById('conf-pfqty').value=avail;document.getElementById('conf-reject').value=0;const f=document.getElementById('conf-finish');if(o.output_type==='SOUPLE'){f.value='GAINE_SEULE';f.disabled=true}else f.disabled=false};src.addEventListener('change',fill);fill();document.getElementById('conf-pfqty').addEventListener('input',()=>{document.getElementById('conf-reject').value=Math.max(num(document.getElementById('conf-in').value)-num(document.getElementById('conf-pfqty').value),0)});document.getElementById('conf-validate').addEventListener('click',validateConfection)}document.getElementById('conf-close').addEventListener('click',closeOF);
}
async function validateConfection(){const src=document.getElementById('conf-source').value,finish=document.getElementById('conf-finish').value,qin=+document.getElementById('conf-in').value,qpf=+document.getElementById('conf-pfqty').value,rej=+document.getElementById('conf-reject').value;const cons=[...document.querySelectorAll('.conf-real')].map(x=>({component_id:x.dataset.id,actual_qty:num(x.value),pru:num(document.querySelector(`.conf-pru[data-id="${x.dataset.id}"]`).value)})).filter(x=>x.actual_qty>0);const {error}=await supabaseClient.rpc('validate_confection_batch',{p_of_id:currentOFId,p_source_output_id:src,p_finished_article_id:document.getElementById('conf-pf').value,p_finish_type:finish,p_qty_input:qin,p_qty_finished:qpf,p_qty_reject:rej,p_consumptions:cons});if(error)return banner('ofd-banner',error.message,'warning');banner('ofd-banner','✅ Lot confection validé et produit fini entré en stock.','success');await loadOFDetail();}
async function closeOF(){const {error}=await supabaseClient.rpc('close_production_order',{p_of_id:currentOFId});if(error)return banner('ofd-banner',error.message,'warning');banner('ofd-banner','✅ OF terminé.','success');await loadOFDetail();await renderDashboard();}
function renderOFTrace(moves){document.getElementById('ofd-tab-trace').innerHTML=`<div class="panel"><div class="panel-head"><h3>Mouvements liés à l'OF</h3></div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Article</th><th>De</th><th>Vers</th><th>Qté</th><th>Référence</th></tr></thead><tbody>${moves.length?moves.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString('fr-FR')}</td><td>${m.movement_type}</td><td>${esc(m.article?.code)}</td><td>${esc(m.atelier_from||'—')}</td><td>${esc(m.atelier_to||'—')}</td><td>${m.qty} ${esc(m.unite)}</td><td>${esc(m.reference||'—')}</td></tr>`).join(''):'<tr><td colspan="7">Aucun mouvement.</td></tr>'}</tbody></table></div></div>`}

// ---------- Stock réel ----------
async function initStockModule(){const arts=await qArticles();const sel=document.getElementById('mv-article');if(sel)sel.innerHTML=arts.filter(a=>a.gestion_stock!==false).map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.designation||a.intitule)}</option>`).join('');const site=document.getElementById('mv-site');if(site)site.innerHTML=SITES.map(s=>`<option>${s.code}</option>`).join('');const d=document.getElementById('mv-date');if(d&&!d.value)d.value=new Date().toISOString().slice(0,10);await renderMovementList();}
async function saveManualMovement(){const type=document.getElementById('mv-type-entree').checked?'ENTREE':'SORTIE',article_id=document.getElementById('mv-article').value,qty=num(document.getElementById('mv-quantite').value);if(!article_id||qty<=0)return banner('mv-banner','Article et quantité positive obligatoires.','warning');const art=(await qArticles()).find(a=>a.id===article_id);const payload={article_id,movement_type:type,atelier_from:type==='SORTIE'?'STOCK':null,atelier_to:type==='ENTREE'?'STOCK':null,qty,unite:art?.unite||'pièce',reference:document.getElementById('mv-reference').value||null,motif:document.getElementById('mv-motif').value,site:document.getElementById('mv-site').value,movement_date:document.getElementById('mv-date').value,note:document.getElementById('mv-note').value||null,pru:art?.pru_reference||0};const {error}=await supabaseClient.from('stock_movements').insert(payload);if(error)return banner('mv-banner',error.message,'warning');banner('mv-banner','✅ Mouvement enregistré.','success');document.getElementById('mv-quantite').value='';await renderMovementList();}
async function renderMovementList(){const tb=document.getElementById('mv-list-body');if(!tb)return;const {data,error}=await supabaseClient.from('stock_movements').select('*,article:articles!stock_movements_article_id_fkey(*)').order('created_at',{ascending:false}).limit(50);if(error){tb.innerHTML=`<tr><td colspan="8">${esc(error.message)}</td></tr>`;return}tb.innerHTML=(data||[]).length?(data||[]).map(m=>`<tr><td>${new Date(m.movement_date||m.created_at).toLocaleDateString('fr-FR')}</td><td>${esc(m.article?.code)}</td><td>${esc(m.site||'—')}</td><td>${m.movement_type}</td><td>${esc(m.motif||'—')}</td><td>${m.qty} ${esc(m.unite)}</td><td>${esc(m.reference||'—')}</td><td>${m.of_id?'OF':'Manuel'}</td></tr>`).join(''):'<tr><td colspan="8">Aucun mouvement.</td></tr>';}
let integratedStockResults=[];
async function getStockRows(societe='',site='',dateRef=''){const arts=await qArticles();let mq=supabaseClient.from('stock_movements').select('*');if(dateRef)mq=mq.lte('movement_date',dateRef);if(site)mq=mq.or(`site.eq.${site},site.is.null`);const {data:m,error}=await mq;if(error)throw error;const sums={};(m||[]).forEach(x=>{const sign=x.movement_type==='ENTREE'?1:(x.movement_type==='SORTIE'||x.movement_type==='CHUTE'?-1:0);sums[x.article_id]=(sums[x.article_id]||0)+sign*num(x.qty)});return arts.filter(a=>a.gestion_stock!==false&&(!societe||a.societe===societe)&&(!site||(a.sites||[]).includes(site)||a.article_type==='BLOC'||a.article_type==='MP'||a.article_type==='PSF'||a.article_type==='PF')).map(a=>{let pru=num(a.pru_reference);if(!pru&&typeof computeCoutStandard==='function'){const c=computeCoutStandard({nature:a.nature,volumeMousse:a.volume_mousse,tissus:a.tissus,quantiteTissus:a.quantite_tissus,gaineOui:a.gaine_oui});pru=num(c.total)}const q=sums[a.id]||0;return {code:a.code,intitule:a.intitule||a.designation,sites:(a.sites||[]).join(', '),dateRef,quantite:q,pru,valeur:q*pru,societe:a.societe||'—',categorie:a.categorie||a.article_type,site:site||((a.sites||[])[0]||'—')}})}
async function renderStockExtraction(){const tb=document.getElementById('stock-body');tb.innerHTML='<tr><td colspan="7">Chargement…</td></tr>';try{integratedStockResults=await getStockRows(document.getElementById('stock-societe').value,document.getElementById('stock-site').value,document.getElementById('stock-date-ref').value);tb.innerHTML=integratedStockResults.length?integratedStockResults.map(r=>`<tr><td><strong>${esc(r.code)}</strong></td><td>${esc(r.intitule)}</td><td>${esc(r.sites||'—')}</td><td>${r.dateRef?formatDateFr(r.dateRef):'—'}</td><td>${nfmt(r.quantite,3)}</td><td>${fmtMga(r.pru)}</td><td>${fmtMga(r.valeur)}</td></tr>`).join(''):'<tr><td colspan="7">Aucun article.</td></tr>';}catch(e){tb.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}

// ---------- Budget / valorisation ----------
let lastBudget=[];
async function renderBudget(){const date=document.getElementById('budget-date-ref').value,soc=document.getElementById('budget-societe').value;try{lastBudget=await getStockRows(soc,'',date);const positive=lastBudget.filter(r=>r.quantite!==0),value=positive.reduce((s,r)=>s+r.valeur,0),qty=positive.reduce((s,r)=>s+r.quantite,0);document.getElementById('budget-kpi-grid').innerHTML=`<div class="kpi-card"><div class="label">Valeur stock</div><div class="value">${Math.round(value).toLocaleString('fr-FR')}</div><div class="delta">MGA</div></div><div class="kpi-card"><div class="label">Articles mouvementés</div><div class="value">${positive.length}</div></div><div class="kpi-card"><div class="label">Quantité nette</div><div class="value">${nfmt(qty,1)}</div></div>`;renderBudgetGroup('budget-societe-body',positive,'societe',value);renderBudgetGroup('budget-site-body',positive,'site',value);renderBudgetGroup('budget-categorie-body',positive,'categorie',value);document.getElementById('budget-top-body').innerHTML=positive.sort((a,b)=>b.valeur-a.valeur).slice(0,20).map(r=>`<tr><td>${esc(r.code)}</td><td>${esc(r.intitule)}</td><td>${esc(r.societe)}</td><td>${esc(r.sites||'—')}</td><td>${nfmt(r.quantite,2)}</td><td>${fmtMga(r.pru)}</td><td>${fmtMga(r.valeur)}</td></tr>`).join('')||'<tr><td colspan="7">Aucun stock valorisé.</td></tr>';}catch(e){banner('budget-banner',e.message,'warning')}}
function renderBudgetGroup(id,rows,key,total){const g={};rows.forEach(r=>{const k=r[key]||'—';if(!g[k])g[k]={articles:0,qty:0,val:0};g[k].articles++;g[k].qty+=r.quantite;g[k].val+=r.valeur});document.getElementById(id).innerHTML=Object.entries(g).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.articles}</td><td>${nfmt(v.qty,2)}</td><td>${fmtMga(v.val)}</td><td>${total?((v.val/total)*100).toFixed(1):0}%</td></tr>`).join('')||'<tr><td colspan="5">—</td></tr>'}
function exportBudget(){if(!lastBudget.length)return alert('Actualisez le budget avant export.');downloadCsv('budget_stock_vitafoam.csv',[['Code','Intitulé','Société','Sites','Quantité','PRU','Valeur'],...lastBudget.map(r=>[r.code,r.intitule,r.societe,r.sites,r.quantite,Math.round(r.pru),Math.round(r.valeur)])]);}

// ---------- Branchements ----------
document.addEventListener('DOMContentLoaded',()=>{
  const cat=document.getElementById('art-categorie');if(cat&&!cat.querySelector('option[value="SF"]')){const o=document.createElement('option');o.value='SF';o.textContent='SF — Semi-fini mousse';cat.insertBefore(o,cat.querySelector('option[value="NEG"]'));}
  // Etendre la règle de caractéristiques aux SF via interception simple
  try{const oldCat=categorieUtiliseCaracteristiques;window.categorieUtiliseCaracteristiques=(c)=>oldCat(c)||c==='SF';}catch(e){}
  document.getElementById('prod-action-new-of')?.addEventListener('click',async()=>{showView('of-new');await initOFCreate()});
  document.getElementById('prod-action-bom')?.addEventListener('click',async()=>{showView('bom');await initBom()});
  document.getElementById('prod-action-refresh')?.addEventListener('click',renderDashboard);
  document.getElementById('of-create-btn')?.addEventListener('click',createOF);
  document.getElementById('bom-parent')?.addEventListener('change',e=>loadBom(e.target.value));
  document.getElementById('bom-save-btn')?.addEventListener('click',saveBom);
  document.getElementById('of-detail-back')?.addEventListener('click',async()=>{showView('dash');await renderDashboard()});
  document.querySelectorAll('#ofd-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#ofd-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.ofd-tab').forEach(x=>x.classList.add('hidden'));document.getElementById('ofd-tab-'+b.dataset.tab).classList.remove('hidden')}));
  document.getElementById('nav-stock')?.addEventListener('click',initStockModule);
  document.getElementById('mv-save-btn')?.addEventListener('click',saveManualMovement);
  const bd=document.getElementById('budget-date-ref');if(bd&&!bd.value)bd.value=new Date().toISOString().slice(0,10);
  document.getElementById('nav-budget')?.addEventListener('click',renderBudget);
  document.getElementById('budget-actualiser-btn')?.addEventListener('click',renderBudget);
  document.getElementById('budget-export-btn')?.addEventListener('click',exportBudget);
});


window.VitafoamProduction = {
  renderDashboard,
  initOFCreate,
  initBom,
  openOF,
  initStockModule,
  renderStockExtraction,
  renderBudget
};
})();
